import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"
import { getServerSession } from "next-auth"
import SessionProvider from "../components/SessionProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Next-Auth tutorial",
	description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
	const session = await getServerSession()
	return (
		<SessionProvider session={session}>
			<html lang="en">
				<body className={`${inter.className} px-[5%] mx-auto`}>
					<Navbar />
					{children}
				</body>
			</html>
		</SessionProvider>
	)
}
